import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Layout/Header";
import { JotaiProvider } from "@/providers/jotai-provider";
import Footer from "../components/Layout/Footer";
import { ThemeProvider } from "@/providers/theme-provider";
import { ScrollProvider } from "@/providers/scroll-provider";
import { cn } from "@/utils/cn";
import { UtilityButtons } from "@/components/Layout/UtilityButtons";

type RootLayoutProps = {
    children: React.ReactNode;
};

const inter = Inter({ subsets: ["latin"] });

// TODO: metadata
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en" style={{ colorScheme: 'dark' }} className={cn('dark')} suppressHydrationWarning>
        <body className={inter.className}>
        <JotaiProvider>
            <ThemeProvider>
                <ScrollProvider>
                    <Header />
                    {children}
                    <Footer />
                    <UtilityButtons />
                </ScrollProvider>
            </ThemeProvider>
        </JotaiProvider>
        </body>
        </html>
    );
}
