site_info:
  author: cocdeshijie
  profile_image: "/static/next-sakurairo.png"
  theme_color: "#FFAAA7"
  theme_color_hue_shift: 30

posts_config:
  posts_per_page: 4

header_logo:
  text_front: cocdeshijie
  text_middle: の
  text_end: Blog
  text_bottom: qwq~

header_navigation:
  - title: Home
    href: "/"
  - title: Tags
    href: "/tags"
  - title: Posts
    href: "/posts"
  - title: Dropdown
    href: "/"
    children:
      - title: Example
        href: "https://example.com"
      - title: Example 2
        href: "https://example.com"

home_working_on:
  - Python
  - TypeScript
  - C++
  - React
  - FastAPI
  - Next.js

home_social:
  - name: GitHub
    src: "/static/social-icons/github.svg"
    href: "https://github.com/cocdeshijie"
  - name: X
    src: "/static/social-icons/x.svg"
    href: "https://twitter.com/cocdeshijie"
  - name: BiliBili
    src: "/static/social-icons/bilibili.svg"
    href: "https://space.bilibili.com/60559166"
  - name: Telegram
    src: "/static/social-icons/telegram.svg"
    href: "https://telegram.me/cocdeshijie"
  - name: Discord
    src: "/static/social-icons/discord.svg"
    href: "https://discordapp.com/channels/@me/390338482951815178/"
  - name: QQ
    src: "/static/social-icons/qq.svg"
    href: "tencent://message/?uin=2049302246"
  - name: Steam
    src: "/static/social-icons/steam.svg"
    href: "https://steamcommunity.com/id/cocdeshijie"

footer:
  line_1:
    - text: Placeholder
      href: "/"
    - text: Placeholder
      href: "/"
    - text: Placeholder
      href: "/"
    - text: Placeholder
      href: "/"
  line_2: Placeholder text
  line_3: Additional text
