site_info:
  title: Next Sakurairo
  author: cocdeshijie
  profile_image: "/static/next-sakurairo.png"
  theme_color: "#FFAAA7"
  theme_color_hue_shift: 30

posts_config:
  posts_per_page: 4

header_logo:
  text_front: Next Sakurairo
  text_middle: の
  text_end: Site
  text_bottom: work in progress~

header_navigation:
  - title: Home
    href: "/"
  - title: Tags
    href: "/tags"
  - title: Posts
    href: "/posts"
  - title: Preview
    href: "/"
    children:
      - title: Post Preview
        href: "/posts/markdown-preview"
      - title: Page Preview
        href: "/page-preview"
      - title: Folder Routing Preview
        href: "/folder/page-folder-preview"
      - title: AniList Preview
        href: "/anilist-preview"

home_working_on:
  - Next.js
  - Tailwind CSS
  - TypeScript
  - Jotai
  - Radix UI
  - Velite

home_social:
  - name: GitHub
    src: "/static/social-icons/github.svg"
    href: "https://github.com/cocdeshijie/Next-Sakurairo"
  - name: X
    src: "/static/social-icons/x.svg"
    href: "/"
  - name: BiliBili
    src: "/static/social-icons/bilibili.svg"
    href: "/"
  - name: Telegram
    src: "/static/social-icons/telegram.svg"
    href: "/"
  - name: Discord
    src: "/static/social-icons/discord.svg"
    href: "/"
  - name: QQ
    src: "/static/social-icons/qq.svg"
    href: "/"
  - name: Steam
    src: "/static/social-icons/steam.svg"
    href: "/"

footer:
  line_1:
    - text: Home
      href: "/"
    - text: Post Preview
      href: "/posts/markdown-preview"
    - text: Page Preview
      href: "/page-preview"
    - text: Folder Routing Preview
      href: "/folder/page-folder-preview"
    - text: AniList Preview
      href: "/anilist-preview"
    - text: Tags
      href: "/tags"
  line_2: 誰でも大好き!
  line_3: qwq~

# see https://giscus.app/ for options
giscus:
  repo: cocdeshijie/Next-Sakurairo
  repo_id: R_kgDOLtf1_A
  category: Announcements
  category_id: DIC_kwDOLtf1_M4Cpnbn
  mapping: url
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: bottom
  theme: preferred_color_scheme
  lang: en