header_logo:
  text_front: cocdeshijie
  text_middle: の
  text_end: Blog
  text_bottom: qwq~

header_navigation:
  - title: Home
    href: ""
  - title: Placeholder
    href: ""
  - title: Posts
    href: ""
  - title: About
    href: ""
    children:
      - title: me
        href: ""
      - title: this site
        href: ""

home_social:
  - name: GitHub
    src: "/static/social-icons/github.svg"
    href: "https://github.com/cocdeshijie"
  - name: X
    src: "/static/social-icons/x.svg"
    href: "https://twitter.com/cocdeshijie"
  - name: BiliBili
    src: "/static/social-icons/bilibili.svg"
    href: "https://space.bilibili.com/60559166"
  - name: Telegram
    src: "/static/social-icons/telegram.svg"
    href: "https://telegram.me/cocdeshijie"
  - name: Discord
    src: "/static/social-icons/discord.svg"
    href: "https://discordapp.com/channels/@me/390338482951815178/"
  - name: QQ
    src: "/static/social-icons/qq.svg"
    href: "tencent://message/?uin=2049302246"
  - name: Steam
    src: "/static/social-icons/steam.svg"
    href: "https://steamcommunity.com/id/cocdeshijie"
