site_info:
  title: cocdeshijie の Blog
  author: cocdeshijie
  profile_image: "/static/cocdeshijie.png"
  theme_color: "#F08300"
  theme_color_hue_shift: 0

posts_config:
  posts_per_page: 6

header_logo:
  text_front: cocdeshijie
  text_middle: の
  text_end: blog
  text_bottom: qwq~

header_navigation:
  - title: Home
    href: "/"
  - title: Posts
    href: "/posts"
  - title: About
    href: "/about-me"
    children:
      - title: About Me
        href: "/about-me"
      - title: My Anime List
        href: "/anime-list"

home_working_on:
  - Next.js
  - Tailwind CSS
  - TypeScript
  - React
  - Python
  - FastAPI
  - C++
  - Java
  - JavaScript
  - MySQL
  - MongoDB
  - Docker
  - SolidWorks
  - Fusion 360
  - Matlab

home_social:
  - name: GitHub
    src: "/static/social-icons/github.svg"
    href: "https://github.com/cocdeshijie/Next-Sakurairo"
  - name: X
    src: "/static/social-icons/x.svg"
    href: "https://x.com/cocdeshijie"
  - name: BiliBili
    src: "/static/social-icons/bilibili.svg"
    href: "https://space.bilibili.com/60559166"
  - name: Telegram
    src: "/static/social-icons/telegram.svg"
    href: "https://t.me/cocdeshijie"
  - name: Discord
    src: "/static/social-icons/discord.svg"
    href: "https://discordapp.com/users/390338482951815178"
  - name: Steam
    src: "/static/social-icons/steam.svg"
    href: "https://steamcommunity.com/id/cocdeshijie"

footer:
  line_1:
    - text: Home
      href: "/"
    - text: Posts
      href: "/posts"
    - text: About Me
      href: "/about-me"
    - text: My Anime List
      href: "/anime-list"
  line_2: 誰でも大好き!
  line_3: qwq~

# see https://giscus.app/ for options
giscus:
  repo: cocdeshijie/qwq.xyz
  repo_id: R_kgDOJ4T77A
  category: Announcements
  category_id: DIC_kwDOJ4T77M4CXyVU
  mapping: url
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: bottom
  theme: preferred_color_scheme
  lang: en